In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
true_news = pd.read_csv(r"News_dataset\True.csv")
fake_news = pd.read_csv(r"News_dataset\Fake.csv")

In [3]:
true_news.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [4]:
fake_news.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
true_news['is_fake'] = 0
fake_news['is_fake'] = 1

In [6]:
print(true_news.head())
print(fake_news.head())

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date  is_fake
0  December 31, 2017         0
1  December 29, 2017         0
2  December 31, 2017         0
3  December 30, 2017         0
4  December 29, 2017         0
                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date  is_fake
0  December 31, 2017        1
1  December 31, 2017        1
2  December 30, 2017        1
3  December 29, 2017        1
4  December 25, 2017        1

In [7]:
print("fake news: ",fake_news.shape)
print("\ntrue news: ",true_news.shape)

fake news:  (23481, 5)

true news:  (21417, 5)

In [8]:
df = pd.concat([true_news, fake_news], ignore_index=True)

In [9]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [10]:
df.head()

,title,text,subject,date,is_fake
0,BREAKING: GOP Chairman Grassley Has Had Enoug...,"Donald Trump s White House is in chaos, and th...",News,"July 21, 2017",1
1,Failed GOP Candidates Remembered In Hilarious...,Now that Donald Trump is the presumptive GOP n...,News,"May 7, 2016",1
2,Mike Pence’s New DC Neighbors Are HILARIOUSLY...,Mike Pence is a huge homophobe. He supports ex...,News,"December 3, 2016",1
3,California AG pledges to defend birth control ...,SAN FRANCISCO (Reuters) - California Attorney ...,politicsNews,"October 6, 2017",0
4,AZ RANCHERS Living On US-Mexico Border Destroy...,Twisted reasoning is all that comes from Pelos...,politics,"Apr 25, 2017",1

In [11]:
df['is_fake'].value_counts()

is_fake
1    23481
0    21417
Name: count, dtype: int64

In [12]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
is_fake    0
dtype: int64

In [13]:
df['subject'].value_counts()

subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64

In [14]:
df.duplicated().sum()

np.int64(209)

In [15]:
df = df.drop_duplicates()

In [16]:
df.shape

(44689, 5)

In [17]:
df['content'] = df['title'] + " " + df['text']

In [18]:
df.head()

,title,text,subject,date,is_fake,content
0,BREAKING: GOP Chairman Grassley Has Had Enoug...,"Donald Trump s White House is in chaos, and th...",News,"July 21, 2017",1,BREAKING: GOP Chairman Grassley Has Had Enoug...
1,Failed GOP Candidates Remembered In Hilarious...,Now that Donald Trump is the presumptive GOP n...,News,"May 7, 2016",1,Failed GOP Candidates Remembered In Hilarious...
2,Mike Pence’s New DC Neighbors Are HILARIOUSLY...,Mike Pence is a huge homophobe. He supports ex...,News,"December 3, 2016",1,Mike Pence’s New DC Neighbors Are HILARIOUSLY...
3,California AG pledges to defend birth control ...,SAN FRANCISCO (Reuters) - California Attorney ...,politicsNews,"October 6, 2017",0,California AG pledges to defend birth control ...
4,AZ RANCHERS Living On US-Mexico Border Destroy...,Twisted reasoning is all that comes from Pelos...,politics,"Apr 25, 2017",1,AZ RANCHERS Living On US-Mexico Border Destroy...

In [19]:
df['content'] = df['content'].apply(lambda x:x.lower())

In [20]:
df['content']

0         breaking: gop chairman grassley has had enoug...
1         failed gop candidates remembered in hilarious...
2         mike pence’s new dc neighbors are hilariously...
3        california ag pledges to defend birth control ...
4        az ranchers living on us-mexico border destroy...
                               ...
44892    new york protesters camp out at goldman sachs ...
44894    boiler room #62 – fatal illusions tune in to t...
44895    atheists sue governor of texas over display on...
44896    republican tax plan would deal financial hit t...
44897    u.n. refugee commissioner says australia must ...
Name: content, Length: 44689, dtype: str

In [21]:
## remove emojii

def remove_emoji(txt):
    new = " "
    for i in txt:
        if i.isascii():
            new+=i

    return new


df['content'] = df['content'].apply(remove_emoji)

In [22]:
import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

df['content'] = df['content'].apply(remove_punc)

In [23]:
df['content']

0          breaking gop chairman grassley has had enoug...
1          failed gop candidates remembered in hilariou...
2          mike pences new dc neighbors are hilariously...
3         california ag pledges to defend birth control...
4         az ranchers living on usmexico border destroy...
                               ...
44892     new york protesters camp out at goldman sachs...
44894     boiler room 62  fatal illusions tune in to th...
44895     atheists sue governor of texas over display o...
44896     republican tax plan would deal financial hit ...
44897     un refugee commissioner says australia must s...
Name: content, Length: 44689, dtype: str

In [24]:
import re

def remove_urls(text):
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    return text


df['content'] = df['content'].apply(remove_urls)

In [25]:
def remove_html(text):
    text = re.sub(r'<.*?>', '', text)
    return text

df['content'] = df['content'].apply(remove_html)